openapi: 3.0.0
info:
  title: GSIRWH
  version: '1.0'
  contact:
    name: Tamaghna Banerjee
    email: '+918478896944'
  description: GSIRWH API WEB SERVICE
servers:
  - url: 'https://findela.com'
    description: Rain Water Harvesting
paths:
  /user/register:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      description: ''
    post:
      summary: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type:
                      - string
                      - object
                    properties:
                      userDetails:
                        type:
                          - string
                          - object
                        properties:
                          mobileNumber:
                            type: number
                          firstName:
                            type: string
                          lastName:
                            type: string
                          userId:
                            type: number
                          createdAt:
                            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                mobileNumber:
                  type: integer
                userType:
                  type: string
            examples:
              sample request:
                value:
                  firstName: Chandan
                  lastName: Kumar
                  mobileNumber: 1212121212
                  userType: CUSTOMER
        description: ''
      parameters: []
    parameters: []
components:
  schemas: {}
  securitySchemes: {}
